project:
  type: website
  output-dir: docs

lang: es

website:
  title: "Nefro-CLM"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Inicio
      - text: Análisis
        menu:
        - href: trasplantes.qmd
          text: Trasplantes renales
        - href: espera.qmd
          text: Lista de espera renal
        - href: presupuestos.qmd
          text: Presupuestos de hemodiálisis
        - href: sources.qmd
          text: Referencias
      - href: about.qmd
        text: Sobre la web

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false

