project:
  type: website
  output-dir: docs

lang: es

website:
  title: "Nefro-CLM"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Análisis
        menu:
        - href: trasplantes.qmd
          text: Trasplantes renales
      - href: about.qmd
        text: Sobre la web

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



