---
title: "Referencias"
---

## Análisis de los trasplantes renales

### Informes de la ONT {#sec-informes-ont}

Informes "Actividad de donación y trasplante renal en España" de la Organización Nacional de Trasplantes (ONT):

- [Informe 2025](documentos/informes-ont/ACTIVIDAD-DE-DONACION-Y-TRASPLANTE-RENAL-ESPANA-2025%20-%201.pdf)
- [Informe 2024](documentos/informes-ont/ACTIVIDAD-DE-DONACION-Y-TRASPLANTE-RENAL-ESPANA-2024.pdf)
- [Informe 2023](documentos/informes-ont/DONACION-Y-TRASPLANTE-RENAL-2023.pdf)
- [Informe 2022](documentos/informes-ont/DONACION-Y-TRASPLANTE-RENAL-2022.pdf)
- [Informe 2021](documentos/informes-ont/Actividad-de-Donacion-y-Trasplante-Renal-en-Espana-2021.pdf)
- [Informe 2020](documentos/informes-ont/Actividad-de-Donacion-y-Trasplante-Renal-2020.pdf)

## Análisis presupuestarios {#sec-presupuestos}

Ejecución Presupuestaria Mensual de las Comunidades Autónomas:

- [2024](documentos/presupuestos/2024.pdf)
- [2023](documentos/presupuestos/2023.pdf)
- [2022](documentos/presupuestos/2022.pdf)
- [2021](documentos/presupuestos/2021.pdf)
- [2020](documentos/presupuestos/2020.pdf)
- [2019](documentos/presupuestos/2019.pdf)
- [2018](documentos/presupuestos/2018.pdf)
- [2017](documentos/presupuestos/2017.pdf)
- [2016](documentos/presupuestos/2016.pdf)