renv::install("tidyverse")
renv::install("plotly")
renv::install("here")
renv::install("bslib")
renv::install("shiny")
renv::install("rvest")
renv::install("httr2")
renv::install("xml2")
renv::install("tabulapdf")
renv::install("janitor")
renv::install("cli")
renv::install("scales")

renv::snapshot()
